### ISSUE TITLE
Omnis Backpacks keybind conflicts with Backpacked keybind

### ISSUE THREAD

**Issue by enduum** [SammySemicolon/Backpack-Mod#1]
If Omnis Backpacks is present alongside MrCrayfish's [Backpacked](https://www.curseforge.com/minecraft/mc-mods/backpacked), the keybind to open the Omnis backpack seems to override the Backpacked keybind. Emphasis on _seems._ By default both backpacks are bound to B. No matter what keys I bind either backpack to, the Omnis backpack can be opened but Backpacked's cannot. This occurs whether both packs are equipped not, the Backpacked pack still can't be opened after unequipping the Omnis pack.
Additionally, after closing and relaunching the game, the Backpacked key will have been rebound to whatever Omnis is bound to.  Eg, if I set Omnis to O and Backpacked to B, on reopening the game both packs will be bound to O.

Removing Omnis Backpack makes the Backpacked pack functional again, it'll still be bound to whatever key Omnis was using though.

One caveat: When I made a clean instance to test this, the _very first_ time I launched the game and equipped both backpacks, I was able to press B and have each pack open in quick succession. One pack opened first, and when I closed it the other opened. But I haven't been able to recreate this since :v

Minecraft: 1.16.5
Omnis Backpacks: 1.1.0
Backpacked: 1.10.0
Curios: 4.0.5.1 (optional dependency for Backpacked, issue occurs with or without)
Tested on a clean install with no other mods
I'll link MrCrayfish to this issue as well

~~don't ask why i have so many backpacks. i have a lot of stuff ok~~

**Comment by SammySemicolon** [comment]
I think I understand what the problem is, I'll upload a fixed version soon! <3
