### ISSUE TITLE
Backpack dupes itself

### ISSUE THREAD

**Issue by GasVar** [SammySemicolon/Backpack-Mod#2]
So whenever I leave my world and rejoin the backpack gets off my back slot (not chestplate slot) and dupes itself, has happend 4 times, it basically dupes with all the items inside and only happens when I rejoin my world after a while of being off
![image](https://user-images.githubusercontent.com/85769995/121756015-244db900-caef-11eb-8f47-21b4c95271e1.png)

**Comment by SammySemicolon** [comment]
First off, what the hell is happening in that image. Second off, I'll fix it asap.
