### ISSUE TITLE
Netherite Backpack is destroyed in lava

### ISSUE THREAD

**Issue by COLDW0LF** [SammySemicolon/Backpack-Mod#3]
Throwing a Netherite backpack into lava destroys it immediately.
I'm assuming this is an issue and not intentional!

**Comment by SammySemicolon** [comment]
It is a bug, yeah.

**Comment by SammySemicolon** [comment]
Fixed in most recent version, I'll release it soon-ish-maybe ?

**Comment by COLDW0LF** [comment]
Awesome, thank you so much!
Love the backpack designs, by the way... super cool mod!
